# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RemoverRuido.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'RemoverRuido.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RemoverRuido.proto\x12\x0cremoverruido\",\n\rReduceRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x0c\n\x04rate\x18\x02 \x01(\x05\"\x1c\n\x0bReduceReply\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32Y\n\x0bReduceNoise\x12J\n\x0cNoiseReducer\x12\x1b.removerruido.ReduceRequest\x1a\x1b.removerruido.ReduceRequest\"\x00\x42:\n\x1dio.grpc.examples.removerruidoB\x11RemoverRuidoProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemoverRuido_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035io.grpc.examples.removerruidoB\021RemoverRuidoProtoP\001\242\002\003HLW'
  _globals['_REDUCEREQUEST']._serialized_start=36
  _globals['_REDUCEREQUEST']._serialized_end=80
  _globals['_REDUCEREPLY']._serialized_start=82
  _globals['_REDUCEREPLY']._serialized_end=110
  _globals['_REDUCENOISE']._serialized_start=112
  _globals['_REDUCENOISE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
